# Site settings
name: 轻功雪上飘
location: 长春
company: 一汽-大众
position: Java开发工程师
github: https://github.com/
facebook: https://www.facebook.com/
phone: 1580424XXXX
email: 185538704@qq.com

baseurl: "/github.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

